title = "basingse"
base_url = "https://basingse.org"
description = "todo"

compile_sass = true
minify_html = true
generate_feeds = false
build_search_index = true
author = "Max Gallup"

default_language = "en"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
	{ theme = "solarized-dark", filename = "syntax-theme-dark.css" },
	{ theme = "solarized-light", filename = "syntax-theme-light.css" },
]
smart_punctuation = true
bottom_footnotes = true

[search]
include_title = true
include_description = true
include_date = true
include_path = true
include_content = true
index_format = "elasticlunr_json"


[extra]
# primary_color = "#3584e4"
# primary_color_alpha = "rgba(53, 132, 228, 0.2)"
primary_color = "#59cc8f"
primary_color_alpha = "rgba(26, 204, 143, 0.2)"
primary_color_dark = "#59cc8f"
primary_color_dark_alpha = "rgba(26, 204, 143, 0.2)"

fix_contrast_dark = true
emoji_favicon = "🥬"
issues_url = "https://github.com/maxgallup/basingse/issues"
source_url = "https://github.com/maxgallup/basingse"
# Additional CSS stylesheets; expects them to be in the "./static/" directory.
# If you are using Sass it will be generated there automatically.
# stylesheets = [
#   "YOUR_STYLE.css",
#   "ALSO_YOUR_STYLE.css"
# ]
# Additional JavaScript scripts; expects them to be in the "./static/" directory.
# scripts = [
#   "YOUR_SCRIPT.js",
#   "ALSO_YOUR_SCRIPT.js"
# ]
# Whether to show "copy code" button on all code blocks
# that have the language set.
# See https://www.getzola.org/documentation/content/syntax-highlighting/
show_copy_button = true
# Whether to show estimated read time in posts.
# Calculated using the simple math: number of words ÷ words per minute.
show_read_time = true
# words_per_minute = "200"

[extra.nav]
show_feed = false
show_theme_switcher = true
show_repo = false
# See https://www.getzola.org/documentation/content/linking/#internal-links
links = [
	{ url = "@/blog/_index.md", name = "Blog" },
	{ url = "@/recipes/_index.md", name = "Recipes" },
]

[extra.footer]
show_copyright = false
show_powered_by = false
show_source = false
